Repository Quizeloper/quizeloper-server-user, pull requests merged in 2023-08, with the labels that each got.

#5 #4 feat: Dockerfile 생성
  Dockerfile
Labels: 🌱 infra, 🌸 chaeyeon

#7 [feat] DB 정보 추가
  .gitignore
  build.gradle
  src/main/java/com/cs/quizeloper/QuizeloperApplication.java
  src/main/resources/application.yaml
Labels: 🌱 infra, 🌸 chaeyeon

#12 [feat] 전체 퀴즈 목록 조회 기능 API
  src/main/java/com/cs/quizeloper/global/exception/BaseResponseStatus.java
  src/main/java/com/cs/quizeloper/quiz/Repository/QuizLikeRepository.java
  src/main/java/com/cs/quizeloper/quiz/Repository/QuizRepository.java
  src/main/java/com/cs/quizeloper/quiz/controller/QuizController.java
  src/main/java/com/cs/quizeloper/quiz/entity/Quiz.java
  src/main/java/com/cs/quizeloper/quiz/entity/QuizUnit.java
  src/main/java/com/cs/quizeloper/quiz/entity/QuizUnitList.java
  src/main/java/com/cs/quizeloper/quiz/model/GetPagedQuizRes.java
  src/main/java/com/cs/quizeloper/quiz/model/GetQuizRes.java
  src/main/java/com/cs/quizeloper/quiz/service/QuizService.java
  src/main/resources/application.yaml
Labels: 🌸 chaeyeon, 🖇️ feat

#13 [feat] valid annotation & WebSecurityConfig 생성
  build.gradle
  src/main/java/com/cs/quizeloper/QuizeloperApplication.java
  src/main/java/com/cs/quizeloper/global/config/WebSecurityConfig.java
  src/main/java/com/cs/quizeloper/global/exception/AppExceptionHandler.java
  src/main/java/com/cs/quizeloper/global/exception/BaseResponse.java
Labels: 🌱 infra, 🌷 chae-eun

#18 [feat] redis 설정 + 회원가입 닉네임 정규 표현식 + 토큰 재발급
  build.gradle
  src/main/java/com/cs/quizeloper/global/config/RedisConfig.java
  src/main/java/com/cs/quizeloper/global/jwt/JwtService.java
  src/main/java/com/cs/quizeloper/global/jwt/dto/TokenDto.java
  src/main/java/com/cs/quizeloper/global/service/RedisService.java
  src/main/java/com/cs/quizeloper/user/Repository/UserRepository.java
  src/main/java/com/cs/quizeloper/user/controller/UserController.java
  src/main/java/com/cs/quizeloper/user/dto/SignupReq.java
  src/main/java/com/cs/quizeloper/user/service/UserService.java
Labels: 🌷 chae-eun, 🖇️ feat

#20 [feat] 로그아웃 & 비밀번호 확인
  src/main/java/com/cs/quizeloper/global/constant/Constant.java
  src/main/java/com/cs/quizeloper/global/entity/BaseStatus.java
  src/main/java/com/cs/quizeloper/global/exception/BaseResponseStatus.java
  src/main/java/com/cs/quizeloper/global/jwt/JwtService.java
  src/main/java/com/cs/quizeloper/global/resolver/Auth.java
  src/main/java/com/cs/quizeloper/global/resolver/LoginResolver.java
  src/main/java/com/cs/quizeloper/user/controller/UserController.java
  src/main/java/com/cs/quizeloper/user/dto/IsValidPasswordReq.java
  src/main/java/com/cs/quizeloper/user/dto/SignupReq.java
  src/main/java/com/cs/quizeloper/user/service/UserService.java
Labels: 🌷 chae-eun, 🖇️ feat
